#!/bin/bash


mv ~/Downloads/\^GSPC.csv gspc.csv

####     backup the previous SP data file     ####
    echo "... backup sp500.csv to ./stock_data/sp500backup_$DATE.csv"
    cp sp500.csv ./stock_data/sp500backup_$DATE.csv


#### concatenate the old and new (incremental) sp500 data files ####
    newFile="sp500_new.csv"
    cat gspc.csv | ./awksedfilter > $newFile
    tmpFile="sp500_$$.csv"
    cp sp500.csv $tmpFile
    ./appendTSFiles.py $tmpFile $newFile sp500.csv
    echo "new output filename:  sp500.csv"
    cp sp500.csv ./stock_data/sp500.csv
    rm $tmpFile $newFile


